DidCommV2 doesn't specify 'typ'
sicpa-dlab/didcomm-python pull request #93
Opened 2023-03-08 20:33 UTC by FabioPinheiro

DidCommV2 doesn't specify 'typ'
This makes it incompatible with other implementations

2023-03-08 20:34 UTC, FabioPinheiro commented
I didn't test anything so someone needs to figure out how to make this according to the specification.

2023-03-09 08:51 UTC, yvgny commented
@FabioPinheiro Thanks for your contribution!

From what I read in the specs, DIDComm may use the `typ` field (see https://identity.foundation/didcomm-messaging/spec/#iana-media-types). So maybe we should make this optional instead of removing completely?

2023-03-09 10:40 UTC, FabioPinheiro commented
yes and no

I'm basically only removing the check. The line 105 is still there: https://github.com/sicpa-dlab/didcomm-python/pull/93/files#diff-cb2b8c37b8a59e04819d6634da7909e96a364413c241a5a17a33c5e7685a4c1eR105

However, JOSE specs **recommends** to use `typ` on the outermost envelope to make JOSE structure formats self-describing.

We are adding to the content of the encrypted bytes...

On the outermost envelope, we *can* have `"typ":"application/didcomm-encrypted+json"`

```
{
"ciphertext":"...",
"protected":"eyJlcGsiOnsia3R5IjoiT0tQIiwiY3J2IjoiWDI1NTE5IiwieCI6IndtSU90Sm03MVUwTGI3NDJqYThudFo1NjlGWDlqRjlBVVJ0cm1WYTluU28ifSwiYXB2IjoiLWNOQ3l0eFVrSHpSRE5SckV2Vm05S0VmZzhZcUtQVnVVcVg1a0VLbU9yMCIsInR5cCI6ImFwcGxpY2F0aW9uL2RpZGNvbW0tZW5jcnlwdGVkK2pzb24iLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwiYWxnIjoiRUNESC1FUytBMjU2S1cifQ",
"recipients":[{...}],
"tag":"...",
"iv":"..."
}
```
protected -> is decoded to `{"epk":{"kty":"OKP","crv":"X25519","x":"wmIOtJm71U0Lb742ja8ntZ569FX9jF9AURtrmVa9nSo"},"apv":"-cNCytxUkHzRDNRrEvVm9KEfg8YqKPVuUqX5kEKmOr0","typ":"application/didcomm-encrypted+json","enc":"A256CBC-HS512","alg":"ECDH-ES+A256KW"}
`

But in this implementation `"typ":"application/didcomm-plain+json"` its required to be hard coded on the content (from `ciphertext`).

If you go to all the 'headers' https://identity.foundation/didcomm-messaging/spec/#message-headers and all the additional headers from the DID Comm extensions `typ` does not exist.

So I assume this implementation is unable to decrypt any of the test vectors/examples of the DID Comm v2 Sepc: https://identity.foundation/didcomm-messaging/spec/#appendix-c-test-vectors

2023-03-09 13:31 UTC, FabioPinheiro commented
In `sicpa-dlab/didcomm-jvm` you still have this field... but at least doesn't seem to be a requirement.

https://github.com/sicpa-dlab/didcomm-jvm/blob/993265c75c12924f7ded917e3c54282c327ab315/lib/src/main/kotlin/org/didcommx/didcomm/message/Message.kt#L58

2023-03-13 08:49 UTC, dkulic commented on didcomm/message.py
> +        d["typ"] = DIDCommMessageTypes.PLAINTEXT.value # this is not part of the official specification
If this is optional, I would rather leave it here. Not require it, but always put.

2023-03-13 08:50 UTC, dkulic commented on didcomm/message.py
> -        if d["typ"] != DIDCommMessageTypes.PLAINTEXT.value:
It is important to delete 'typ' if present, not to make problems later.

2023-03-13 08:51 UTC, dkulic commented on didcomm/message.py
> -        if d["typ"] != DIDCommMessageTypes.PLAINTEXT.value:
I am pro this change, but I think we need some changes in this PR. Can you also add some tests for this behaviour (for eg parsing with/without typ)

2023-03-13 08:52 UTC, dkulic requested changes
I am pro these changes, but we need some improvements in this PR. Can we add some tests?

2023-03-13 08:58 UTC, dkulic commented on didcomm/message.py
> -        if d["typ"] != DIDCommMessageTypes.PLAINTEXT.value:
Also, if present, I think we should check its value.

2023-03-30 13:56 UTC, dkulic commented
Closing, because of no activity on this PR, and it is reimplemented here: https://github.com/sicpa-dlab/didcomm-python/pull/96

2023-03-30 13:56 UTC, closed without merging

2023-03-30 14:47 UTC, FabioPinheiro commented
I only do this in my free time and I had very little time on the last three weekends. But important thing is that it's fixed.

But you asked for tests and I was trying to create a test set that everyone could use. Would help us to achieve interoperability at the DID Comm libraries level.

If you could contribute with your test set would be nice https://github.com/decentralized-identity/didcomm.org/issues/77

2023-03-31 07:23 UTC, dkulic commented
No problem Fabio, like you said, it is important that it's fixed now 👍

2023-04-10 15:36 UTC, FabioPinheiro commented
When will there be a release with the fix?

2023-04-12 11:42 UTC, yvgny commented
@FabioPinheiro This will be released as soon as #98 is merged